### ISSUE TITLE
[wf-panel] Autohide (well, "autoshow") is broken on the latest wayfire version

### ISSUE THREAD

**Issue by NamorNiradnug** [WayfireWM/wf-shell#138]
Steps to reproduce:
 - autohide is enabled
 - launch `wf-panel`
   - panel appears and doesn't hide (btw it should)
 - move mouse cursor into the panel's area and then out
   - panel hides
 - move mouse cursor back into the screen edge
   - panel doesn't show but expected to show
   
-----
What I found out:
 - changing `-get_allocated_height()` to `0.001 - get_allocated_height()` [here](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L239) fixes this bug, but it's weird and makes panel not to hide entirely

**Comment by NamorNiradnug** [comment]
Seems like `signal_draw` doesn't emit and the margin doesn't update ([from here](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L34)).
And the signal doesn't emit because `queue_draw()` from [here](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L290) doesn't work when the panel is entirely hidden.

**Comment by ammen99** [comment]
Ah, I see. Wayfire doesn't send a wl_surface.frame_done (which would trigger signal_draw in gtk) event because the panel is fully hidden. That seems the correct behavior from Wayfire's side.

Based on the information you have provided, I have the feeling that the problem is when `m_do_show()` executes, it sets the margin to `y_position` which is animated from its fully hidden state to -1. So in the very first step, we update the margin to fully hidden .. and the next step is never reached, because the panel is hidden and never gets a frame done event. I guess the solution would be to animate the `y_position` from `max(fully-hidden position + 1, y_position.current_value)` to `0` (speaking in pseudo-code), do you mind trying this out to see how well it works?

**Comment by NamorNiradnug** [comment]
Changing [https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L262](this line) to `y_position.animate(y_position + 1, 0);` doesn't work.

**Comment by NamorNiradnug** [comment]
Inserting something like this:
```c++
margin_update = Glib::signal_timeout().connect(
    [=] {
        gtk_layer_set_margin(gobj(), GTK_LAYER_SHELL_EDGE_BOTTOM, y_position);
        std::cout << y_position << std::endl;
        return true;
    }, 30);
```
into [this](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L15) constructor (`margin_update` is a `WayfireAutohidingWindow` member) also doesn't fix the thing. Margin is updated, but the panel is still invisible.

**Comment by NamorNiradnug** [comment]
Does wayfire continue to draw/update a window after it is invisible once?

**Comment by ammen99** [comment]
> Changing [this line](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L262) to `y_position.animate(y_position + 1, 0);` doesn't work.

After a bit of digging in gtk-layer-shell I think I know what the problem is. `set_margin` does not commit the `wl_surface`, so Wayfire never sees that the panel has become visible. As a result, the panel never gets a `wl_surface.frame` event, never renders, etc. I think that adding a `wl_surface_commit()` call after setting the margin could work.

**Comment by NamorNiradnug** [comment]
> > Changing [this line](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L262) to `y_position.animate(y_position + 1, 0);` doesn't work.
> 
> After a bit of digging in gtk-layer-shell I think I know what the problem is. `set_margin` does not commit the `wl_surface`, so Wayfire never sees that the panel has become visible. As a result, the panel never gets a `wl_surface.frame` event, never renders, etc. I think that adding a `wl_surface_commit()` call after setting the margin could work.

Adding `wl_surface_commit(get_wl_surface())` makes is crashes because `this->get_window()` returns `nullptr` because the window is "not released". Adding check `if (get_window())` makes panel to show sometimes.
