### ISSUE TITLE
Dragging files between programs using the window list not working

### ISSUE THREAD

**Issue by Botspot** [WayfireWM/wf-shell#202]
This is a common feature available on other panels and on Windows.
TL;DR it seems that dragging a file from my file manager to another program, by holding the file over that other program's running icon on the window list, does not work.
Pinging @soreau for advice.

**Comment by soreau** [comment]
This probably requires additional protocol that does not exist yet, in wayfire-shell or foreign-toplevel. It would also be a fair amount of work and I don't know this is a good fit for wf-shell/wf-panel, since it's mostly a minimalistic shell. However, patches are welcome, and @ammen99 might have some more insight on the matter.

**Comment by ammen99** [comment]
It is not meant to work like that currently, it will also require a wayfire plugin and a new wayland protocol to coordinate Wayfire, wf-panel and the applications doing the drag-and-drop.

In case someone is interested at some point to implement this:

- A wayfire plugin will need to listen for drag-and-drop on the wlroots seat (we might even want to add an interface to core for this, I think it will be useful, but that is optional)
- Said plugin will need to use a custom protocol/ipc/whatever to tell wf-panel when a drag-and-drop is active, and also will need to send additional input events to wf-panel
- wf-panel will need to report back to the plugin which application is hovered
- the plugin will need to send wl_data_offer (I suppose there are wlr functions for it) to the hovered application, or to bring the application to the front so that you can drop the item on the app

I personally won't have time anytime soon for such a feature, and I'm not sure whether it is worth adding it upstream - it depends on how many people want this feature, so far, you are the first one to request it (or at least, it is the first time I hear of such a request).

**Comment by anoraktrend** [comment]
It's more of a "jump to this maximized app so I can drag and drop into it" kinda thing from reading his Raspberry Pi UI issue. Might be a good idea to support that kinda thing at least.

**Comment by marcusbritanicus** [comment]
@ammen99 @soreau If I am not terribly mistaken, what OP wants is the following: Drag some mime data from one application, move the mouse to the window list, and hover on another application's button. Do not release the mouse button yet: wait for the window to be brought to the top. Then move the mouse to the window and release the button, thus dropping the mime data.

Now, what I do know is D-n-D from one application to another works quite fine on wayland (we already have the protocol and toolkit support for this). What this means is that we can (Qt/Gtk) detect if a D-n-D is happening. So all that needs to be done is when a mouse enters a window list button, just raise the window to the top (or in other words, give it focus).

**Comment by Botspot** [comment]
Precisely.

**Comment by ammen99** [comment]
Well this variation ought to be a bit simpler, you only need to listen for Drag and Drop on the window list and accept any MIME types. PRs welcome :)
