### ISSUE TITLE
latest commits change some expected panel behavior

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wf-shell#252]
seems some of the recent commits changed a few things with the icons on the panel. 

launcher zoom animation is much different (slower it seems). icons are larger by default and spacing between icons has increased.  this is also for system tray icons.  also looks like panel height has increased. 

perhaps i need to adjust some settings in wf-shell.ini now to get things looking like i am used to? 

I see one commit says "remove launcher zoom animation".  I hope not, i really like that animation. it's one of the reasons i am using wf-panel.

**Comment by ammen99** [comment]
Hi, we moved lots of things to CSS which allows for the same effects as before and many others too.

You can configure everything in the css file(s), a default one is installed in `~/.config/wf-shell/css/default.css` there you can configure animation duration.

Also about the icon size, it is a bit weird indeed that it changed, but this is due to the same changes. As a workaround, you can lower the icon size in your wf-shell.ini

By lowering the size in wf-shell.ini and setting the CSS I was able to reproduce the exact same appearance as before, so don't worry, nothing is broken :)

**Comment by trigg** [comment]
My apologies that the documentation took a while to catch up here.

Wiki page generally is [here](https://github.com/WayfireWM/wf-shell/wiki/Style:-overview)

More specifically, you can edit the file `~/.config/wf-shell/css/default.css` and change the `transition` time to anything you like, it will take effect as you save the file.

You could also apply the effect in other parts of the panel if you're interested

**Comment by mrsteve0924** [comment]
thanks for the reply.  i guess i jumped the gun assuming it was a bug when it was a new feature all along :)

i'll start playing around with the css file.
